{% set name = "pyotf" %}
{% set setupdata = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ setupdata.get('version') }}

source:
  # path: ..
  git_url: ../
  git_rev: 'packaging'

build:
  noarch: generic
  number: 0
  string: 'py{{ PY_VER|replace(".", "") }}_{{ PKG_BUILDNUM }}'
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - scikit-image
    - matplotlib

about:
  home: {{ setupdata.get('url') }}
  license: Apache License Version 2.0
  license_file: LICENSE.md
  summary: {{ setupdata.get('description') }}