# conda config --set anaconda_upload yes
# conda build --python 3.8 conda.recipe/

{% set setupdata = load_setup_py_data() %}

package:
  name: pyotf
  version: {{ setupdata['version'] }}

source:
  git_url: ../
  git_rev: v0.0.2

build:
  noarch: python
  number: 0
  script: pip install .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - scikit-image
    - matplotlib
    - tifffile

test:
  imports:
    - pyotf

about:
  home: {{ setupdata['url'] }}
  license: Apache License Version 2.0
  license_file: LICENSE.md
  summary: {{ setupdata['description'] }}
